### ISSUE TITLE
--dynamic does not work for the latest released image

### ISSUE THREAD

**Issue by Trolldemorted** [akarneliuk/prometheus-traceroute-exporter#1]
and I think it's because you did not ship the latest code:

```
/etc/traceroute-exporter # cat bin/helper_functions.py
# (c)2022, Karneliuk.com
# Modules
from argparse import ArgumentParser
import re
import os
from prometheus_client import start_http_server, Gauge
import time


# Functions
def get_instructions():
    parser = ArgumentParser()

    parser.add_argument(
        "-d", "--dev",
        action="store_true",
        default=False,
        help="Test execution with predefined test data.",
    )

    parser.add_argument(
        "-i", "--interval",
        type=int,
        default=60,
        required=False,
        help="Time interval between consequent measurements.",
    )
```

As you can see, the code for that option does not exist.

**Comment by akarneliuk** [comment]
Hello @Trolldemorted ,

Thanks for your message. Could you please advise, how did you download the image? Did you download using no tag (or using `latest` tag) or as provided in example `ghcr.io/akarneliuk/traceroute-exporter:${PLATFORM}` ?

Best,
Anton

**Comment by Trolldemorted** [comment]
I just used `image: ghcr.io/akarneliuk/traceroute-exporter`, is that an older image?

**Comment by akarneliuk** [comment]
Yes, it was. We've just deleted it. Please, download as provided in the example. The reason we have created it in this way is that there are different images for x86_64 and for arm32v7 (Raspberry PI). So the tag allows you to download the image depending on your platform. Take a look here, please: https://github.com/akarneliuk/prometheus-traceroute-exporter/pkgs/container/traceroute-exporter

**Comment by akarneliuk** [comment]
Hey @Trolldemorted ,

please, reopen the ticket if proposed method doesn't work.

Best,
Anton
